#-------------------------------
# General Site Settings

title: Michael's Portfolio
description: Student // Thinker // Creative
email: michael.mugnai@gmail.com

# NOTE: The Logo and Background image are defined in _data/layout.yml,
#       while all styles are defined starting from assets/css/all.sass.

# header and footer links
menu:
- {name: About Me, url: '#about-me'}
- {name: Projects, url: '#work'}
- {name: Contacts, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Michael Mugnai portfolio.'
  rel-author: 'Michael Mugnai'
  rel-publisher: 'Michael Mugnai'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in _data/layout.yml.

blurb: >
  **Michael specializes in making robots** for human people. Even if is still only a student at *University of Pisa*, he has already gained experience on **robotics**, **automation** and **control** through numerous projects and his participation in **FormulaSAE** racing team.


skills:
- {name: Programming, value: '9'}
- {name: Electronics, value: '8'}
- {name: Learning, value: '10'}
- {name: Team-working, value: '8'}
- {name: Rapid prototiping, value: '8'}
- {name: Hardware appeal, value: '9'}



#-------------------------------
# Contact Section

# images from https://fontawesome.com/
social:
- {icon: 'github-alt', link: 'https://github.com/Maik93'}
- {icon: 'gitlab', link: 'https://gitlab.com/maik93'}
- {icon: 'linkedin-in', link: 'https://www.linkedin.com/in/michael-mugnai-a33347185/'}
- {icon: 'telegram-plane', link: 'https://t.me/Maik993'}
- {icon: 'facebook-f', link: 'https://www.facebook.com/maik993'}
